name: Deploy
on:
    push:
      branches:
        - dev
jobs:
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '12'
          - name: Install packages
            run: yarn
          - name: Set Creds
            run: git config user.name "nirajniroula" && git config user.email "niniroula@gmail.com"
          - name: Deploy
            run: yarn deploy
            
